version: "3.8"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - "3001:3001"
  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
      - "3000:3000"
